#include "mesh/mesh.hpp"
#include "shared/attenuation.hpp"
#include "shared/voigt.hpp"

namespace specswd
{

typedef std::complex<float> crealw;

static int c662flat(int m,int n) {
    if(m > n) std::swap(m,n);
    return m * 6 + n - (m * (m + 1)) / 2;
}

/**
 * @brief only set Qkappa and Qmu to C21 
 * @see Carcione and Cavallini (1995d), delta = 2, M3 = M4 = M2 -> Qmu
 */
static void 
C21_iso_(crealw Qk_fac,crealw Qmu_fac,crealw __restrict *c21)
{
    // get kappa and mu by using average
    #define C(p,q) c21[c662flat(p,q)]
    crealw eps = (1.0f/3.0f) * (C(0,0) + C(1,1) + C(2,2));
    crealw mu = (1.0f/3.0f) * (C(3,3) + C(4,4) + C(5,5));
    crealw kappa = eps - (float)(4. / 3.) * mu;

    // add back to c21
    for(int i = 0; i < 3; i ++) {
        C(i,i) = C(i,i) - eps + kappa * Qk_fac + (float)(4./3.) * mu * Qmu_fac;
    }
    for(int i = 0; i < 3; i ++) {
        for(int j = i + 1; j < 3; j ++) {
            C(i,j) = C(i,j) - eps + kappa * Qk_fac + 2.0f* mu * (1.0f - 1.0f/3.0f * Qmu_fac);
        }
    }

    for(int i = 3; i < 6; i ++) C(i,i) *= Qmu_fac;

    #undef C
}

static void 
C21_iso_deriv_(const crealw *Qfac, const crealw *dQfac,
                const float *c21,
                crealw *__restrict dCC21_dc,
                crealw *__restrict dCC21_dQi)
{
    // set derivatives to zero 
    for(int i = 0; i < 21 * 2; i ++) {
        dCC21_dc[i] = 0.;
        dCC21_dQi[i] = 0.;  
    }

    // get kappa and mu fac/dfac 
    std::complex<double> Qk_fac = Qfac[0], Qmu_fac = Qfac[1];
    std::complex<double> dQk_fac = dQfac[0], dQmu_fac = dQfac[1];

    // compute derivatives
    // auto generated by sympy
    #define SETDC(i,j,a) dCC21_dc[i*21+j] = (crealw) (a)
    #define SETDQ(i,j,b) dCC21_dQi[i*2+j] = (crealw) (b)
    #define C(p,q) c21[c662flat(p,q)]
    SETDC(0,0,(1.0/3.0)*Qk_fac + 2.0/3.0);
    SETDC(0,6,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(0,11,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(0,15,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(0,18,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(0,20,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(1,0,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(1,1,1);
    SETDC(1,6,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(1,11,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(1,15,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(1,18,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(1,20,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(2,0,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(2,2,1);
    SETDC(2,6,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(2,11,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(2,15,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(2,18,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(2,20,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(3,3,1);
    SETDC(4,4,1);
    SETDC(5,5,1);
    SETDC(6,0,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(6,6,(1.0/3.0)*Qk_fac + 2.0/3.0);
    SETDC(6,11,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(6,15,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(6,18,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(6,20,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(7,0,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(7,6,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(7,7,1);
    SETDC(7,11,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(7,15,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(7,18,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(7,20,-4.0/9.0*Qk_fac - 2.0/9.0*Qmu_fac + 2.0/3.0);
    SETDC(8,8,1);
    SETDC(9,9,1);
    SETDC(10,10,1);
    SETDC(11,0,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(11,6,(1.0/3.0)*Qk_fac - 1.0/3.0);
    SETDC(11,11,(1.0/3.0)*Qk_fac + 2.0/3.0);
    SETDC(11,15,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(11,18,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(11,20,-4.0/9.0*Qk_fac + (4.0/9.0)*Qmu_fac);
    SETDC(12,12,1);
    SETDC(13,13,1);
    SETDC(14,14,1);
    SETDC(15,15,Qmu_fac);
    SETDC(16,16,1);
    SETDC(17,17,1);
    SETDC(18,18,Qmu_fac);
    SETDC(19,19,1);
    SETDC(20,20,Qmu_fac);

    SETDQ(0,0,((1.0/3.0)*C(0,0)*1. + (1.0/3.0)*C(1,1)*1. + (1.0/3.0)*C(2,2)*1. - 4.0/9.0*C(3,3)*1. - 4.0/9.0*C(4,4)*1. - 4.0/9.0*C(5,5)*1.) * dQk_fac);
    SETDQ(0,1,((4.0/9.0)*C(3,3)*1. + (4.0/9.0)*C(4,4)*1. + (4.0/9.0)*C(5,5)*1.) * dQmu_fac);
    SETDQ(1,0,((1.0/3.0)*C(0,0)*1. + (1.0/3.0)*C(1,1)*1. + (1.0/3.0)*C(2,2)*1. - 4.0/9.0*C(3,3)*1. - 4.0/9.0*C(4,4)*1. - 4.0/9.0*C(5,5)*1.) * dQk_fac);
    SETDQ(1,1,(-2.0/9.0*C(3,3)*1. - 2.0/9.0*C(4,4)*1. - 2.0/9.0*C(5,5)*1.) * dQmu_fac);
    SETDQ(2,0,((1.0/3.0)*C(0,0)*1. + (1.0/3.0)*C(1,1)*1. + (1.0/3.0)*C(2,2)*1. - 4.0/9.0*C(3,3)*1. - 4.0/9.0*C(4,4)*1. - 4.0/9.0*C(5,5)*1.) * dQk_fac);
    SETDQ(2,1,(-2.0/9.0*C(3,3)*1. - 2.0/9.0*C(4,4)*1. - 2.0/9.0*C(5,5)*1.) * dQmu_fac);
    SETDQ(6,0,((1.0/3.0)*C(0,0)*1. + (1.0/3.0)*C(1,1)*1. + (1.0/3.0)*C(2,2)*1. - 4.0/9.0*C(3,3)*1. - 4.0/9.0*C(4,4)*1. - 4.0/9.0*C(5,5)*1.) * dQk_fac);
    SETDQ(6,1,((4.0/9.0)*C(3,3)*1. + (4.0/9.0)*C(4,4)*1. + (4.0/9.0)*C(5,5)*1.) * dQmu_fac);
    SETDQ(7,0,((1.0/3.0)*C(0,0)*1. + (1.0/3.0)*C(1,1)*1. + (1.0/3.0)*C(2,2)*1. - 4.0/9.0*C(3,3)*1. - 4.0/9.0*C(4,4)*1. - 4.0/9.0*C(5,5)*1.) * dQk_fac);
    SETDQ(7,1,(-2.0/9.0*C(3,3)*1. - 2.0/9.0*C(4,4)*1. - 2.0/9.0*C(5,5)*1.) * dQmu_fac);
    SETDQ(11,0,((1.0/3.0)*C(0,0)*1. + (1.0/3.0)*C(1,1)*1. + (1.0/3.0)*C(2,2)*1. - 4.0/9.0*C(3,3)*1. - 4.0/9.0*C(4,4)*1. - 4.0/9.0*C(5,5)*1.) * dQk_fac);
    SETDQ(11,1,((4.0/9.0)*C(3,3)*1. + (4.0/9.0)*C(4,4)*1. + (4.0/9.0)*C(5,5)*1.) * dQmu_fac);
    SETDQ(15,1,(C(3,3)*1.) * dQmu_fac);
    SETDQ(18,1,(C(4,4)*1.) * dQmu_fac);
    SETDQ(20,1,(C(5,5)*1.) * dQmu_fac);

    #undef C 
    #undef SETDC
    #undef SETDQ
}

/**
 * @brief set complex C21 attenuation model
 * @param[inout] c21 real C21 modulus shape(21), return complex modulus
 */
void Mesh::
get_cmplx_c21(const float *Qm,crealw * __restrict c21) const
{
    // get all sls factor
    std::array<crealw,21> Qfac;
    for(int im = 0; im < nQani; im ++) {
        Qfac[im] = get_sls_modulus_factor(freq,Qm[im]);
    }

    // choose sls factor
    switch (Qani_funcid)
    {
    case 1:
        C21_iso_(Qfac[0],Qfac[1],c21);
        break;
    
    default:
        printf("not implemented!\n");
        exit(1);
        break;
    }
}

/**
 * @brief compute derivatives of c21 att model
 * @param Qm Q values, shape(nQani)
 * @param C21 C21 model, shape(21)
 * @param dCC21_dc derivative of complex c21 to real c21, shape (21,21)
 * @param dCC21_dQi derivative of complex c21 to Qi, shape (21,nQani)
 * @param funcid function id, default 1
 */
void Mesh:: 
get_cmplx_c21_deriv(
    float *Qm,
    const float *C21,
    crealw * __restrict dCC21_dc,
    crealw * __restrict dCC21_dQi
) const
{
    // get all sls factor
    std::array<crealw,21> Qfac,dQfac;
    for(int im = 0; im < nQani; im ++) {
        get_sls_Q_derivative(freq,Qm[im],Qfac[im],dQfac[im]);
    }

    switch (Qani_funcid)
    {
    case 1:
        C21_iso_deriv_(Qfac.data(),dQfac.data(),C21,dCC21_dc,dCC21_dQi);
        break;
    
    default:
        printf("not implemented!\n");
        exit(1);
        break;
    }
}

} // namespace name
