name: Build and Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install doc tools
        run: |
          sudo apt install -y doxygen
          pip install sphinx myst-parser sphinx_rtd_theme 

      - name: Build libaries
        run: |
          sudo apt install cmake build-essential gfortran liblapack-dev liblapacke-dev 
          wget https://gitlab.com/libeigen/eigen/-/archive/5.0.0/eigen-5.0.0.tar.gz
          tar -xvf eigen-5.0.0.tar.gz
          pip install pybind11-global
          mkdir -p build
          cd build 
          cmake .. -DCXX=g++ -DFC=gfortran -DEIGEN_INC=./eigen-5.0.0/  -DBUILD_LIBS=ON
          make -j4
          make test
          make install
          cd ..
          
          
      - name: Build Doxygen C++ API Docs
        run: doxygen misc/doxygen/doxygen.cfg 

      - name: Build Python docs (Sphinx)
        run: |
          sphinx-apidoc -o misc/source/python ./specd
          
      - name: Build master docs (Sphinx)
        run: |
          pip install numpy scipy matplotlib numba h5py
           sphinx-build -b html misc/source docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
